#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

from variants import VARIANTS, Variant, host_supported_variants, repo_root
from hwloc_build import ensure_hwloc


MAX_TWIDDLE_REUSE = "8"


def run(cmd: list[str], cwd: Path) -> None:
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def first_existing_tool(candidates: tuple[str, ...]) -> str:
    for candidate in candidates:
        if shutil.which(candidate):
            return candidate
    return candidates[0]


def default_target_tool(name: str) -> str:
    machine = platform.machine().lower()
    if machine in {"x86_64", "amd64"}:
        return name
    return first_existing_tool((f"x86_64-alpine-linux-musl-{name}", f"x86_64-linux-musl-{name}"))


def resolve_tool(tool: str, role: str) -> str:
    resolved = shutil.which(tool)
    if resolved:
        return resolved
    raise SystemExit(
        f"Required {role} tool '{tool}' was not found. "
        "Install the x86_64 musl cross toolchain or pass --cc/--objcopy/--strip explicitly."
    )


def detect_stdflag(cc: str, cwd: Path) -> str:
    for stdflag in ("-std=gnu23", "-std=gnu2x"):
        probe = subprocess.run(
            [cc, stdflag, "-x", "c", "-", "-fsyntax-only"],
            input="constexpr int x = 1; int main(void){return x - 1;}\n",
            text=True,
            cwd=cwd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if probe.returncode == 0:
            return stdflag
    return "-std=gnu11"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def try_generate_proxy_scaling(root: Path, build_root: Path, host_cc: str, stdflag: str, name: str, cflags: list[str]) -> Path | None:
    proxy_dir = build_root / "scaling-proxy" / name
    proxy_dir.mkdir(parents=True, exist_ok=True)
    nufft_obj = proxy_dir / "nufft1.o"
    scaling_gen = proxy_dir / "scaling_gen"
    scaling_header = proxy_dir / "scaling.h"
    common_flags = [stdflag, "-D_GNU_SOURCE", "-DHAS_MIMALLOC=0", f"-DMAX_TWIDDLE_REUSE={MAX_TWIDDLE_REUSE}", "-pthread"]
    include_flags = [f"-I{root / 'include'}", f"-I{root / 'src/nufft'}", f"-I{proxy_dir}", f"-I{root}"]

    try:
        run(
            [
                host_cc,
                *common_flags,
                "-O3",
                "-ffast-math",
                "-fno-sanitize=all",
                *cflags,
                *include_flags,
                "-c",
                str(root / "src/nufft/nufft1.c"),
                "-o",
                str(nufft_obj),
            ],
            root,
        )
        run(
            [
                host_cc,
                *common_flags,
                "-O3",
                "-ffast-math",
                "-fno-sanitize=all",
                *cflags,
                *include_flags,
                str(root / "src/nufft/scaling.c"),
                str(nufft_obj),
                "-static",
                "-lm",
                "-o",
                str(scaling_gen),
            ],
            root,
        )
        run([str(scaling_gen), str(scaling_header)], root)
    except subprocess.CalledProcessError:
        print(f"Scaling proxy {name} could not be generated; falling back if possible.", flush=True)
        return None

    return scaling_header


def arm_proxy_scaling_sources(root: Path, build_root: Path, host_cc: str, stdflag: str) -> dict[str, Path]:
    arm128 = try_generate_proxy_scaling(root, build_root, host_cc, stdflag, "arm128", ["-march=armv8-a+simd"])
    if arm128 is None:
        raise SystemExit("Unable to generate ARM 128-bit proxy scaling for x86 release.")

    arm256 = try_generate_proxy_scaling(root, build_root, host_cc, stdflag, "arm256", ["-march=armv8.2-a+sve", "-msve-vector-bits=256"])
    if arm256 is None:
        arm256 = arm128
        print(f"Scaling proxy arm256: reusing shorter proxy {arm256}", flush=True)

    arm512 = try_generate_proxy_scaling(root, build_root, host_cc, stdflag, "arm512", ["-march=armv8.2-a+sve", "-msve-vector-bits=512"])
    if arm512 is None:
        arm512 = arm256
        print(f"Scaling proxy arm512: reusing shorter proxy {arm512}", flush=True)

    return {
        "x86-64": arm128,
        "x86-64-v2": arm128,
        "x86-64-v2+avx": arm128,
        "x86-64-v3": arm256,
        "x86-64-v4": arm512,
    }


def variant_wrapper_source(variant: Variant) -> str:
    return f"""/* Generated by dispatch/build_release.py. */
#define main __attribute__((visibility("default"))) ihsnpeaks_main_{variant.symbol}
#include "src/main.c"
#include "src/nufft/nufft1.c"
"""


def dispatcher_source(variants: list[Variant]) -> str:
    prototypes = "\n".join(f"int ihsnpeaks_main_{variant.symbol}(int argc, char **argv);" for variant in variants)
    table_rows = "\n".join(
        f'    {{"{variant.name}", "{variant.symbol}", ihsnpeaks_main_{variant.symbol}, supports_{variant.symbol}}},' for variant in reversed(variants)
    )
    alias_rows: list[str] = []
    for variant in variants:
        for alias in (variant.name, variant.symbol, variant.build_name, *variant.aliases):
            alias_rows.append(f'    {{"{alias}", "{variant.name}"}},')
    aliases = "\n".join(alias_rows)

    return f"""/* Generated by dispatch/build_release.py. */
#include <cpuid.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

{prototypes}

typedef int (*ihsnpeaks_entry_fn)(int argc, char **argv);

typedef struct {{
    int v2;
    int v2_avx;
    int v3;
    int v4;
}} ihsnpeaks_cpu_features;

typedef struct {{
    const char *name;
    const char *symbol;
    ihsnpeaks_entry_fn entry;
    int (*supported)(const ihsnpeaks_cpu_features *features);
}} ihsnpeaks_variant_entry;

typedef struct {{
    const char *alias;
    const char *canonical;
}} ihsnpeaks_variant_alias;

static uint64_t ihsnpeaks_xgetbv0(void) {{
    uint32_t eax = 0;
    uint32_t edx = 0;
    __asm__ volatile("xgetbv" : "=a"(eax), "=d"(edx) : "c"(0));
    return ((uint64_t)edx << 32) | eax;
}}

static ihsnpeaks_cpu_features ihsnpeaks_detect_cpu(void) {{
    ihsnpeaks_cpu_features features = {{0}};
    unsigned int eax = 0, ebx = 0, ecx = 0, edx = 0;
    unsigned int max_basic = __get_cpuid_max(0, NULL);
    unsigned int max_extended = __get_cpuid_max(0x80000000U, NULL);

    if (max_basic < 1 || !__get_cpuid(1, &eax, &ebx, &ecx, &edx)) {{
        return features;
    }}

    int has_ssse3 = (ecx & (1U << 9)) != 0;
    int has_fma = (ecx & (1U << 12)) != 0;
    int has_cx16 = (ecx & (1U << 13)) != 0;
    int has_sse4_1 = (ecx & (1U << 19)) != 0;
    int has_sse4_2 = (ecx & (1U << 20)) != 0;
    int has_movbe = (ecx & (1U << 22)) != 0;
    int has_popcnt = (ecx & (1U << 23)) != 0;
    int has_xsave = (ecx & (1U << 26)) != 0;
    int has_osxsave = (ecx & (1U << 27)) != 0;
    int has_avx = (ecx & (1U << 28)) != 0;
    int has_f16c = (ecx & (1U << 29)) != 0;
    int has_lahf_lm = 0;
    int has_lzcnt = 0;

    if (max_extended >= 0x80000001U && __get_cpuid(0x80000001U, &eax, &ebx, &ecx, &edx)) {{
        has_lahf_lm = (ecx & (1U << 0)) != 0;
        has_lzcnt = (ecx & (1U << 5)) != 0;
    }}

    features.v2 = has_cx16 && has_lahf_lm && has_popcnt && has_sse4_1 && has_sse4_2 && has_ssse3;

    uint64_t xcr0 = 0;
    if (has_xsave && has_osxsave) {{
        xcr0 = ihsnpeaks_xgetbv0();
    }}
    int has_avx_state = (xcr0 & 0x6U) == 0x6U;
    features.v2_avx = features.v2 && has_avx && has_xsave && has_osxsave && has_avx_state;

    if (max_basic >= 7 && __get_cpuid_count(7, 0, &eax, &ebx, &ecx, &edx)) {{
        int has_bmi1 = (ebx & (1U << 3)) != 0;
        int has_avx2 = (ebx & (1U << 5)) != 0;
        int has_bmi2 = (ebx & (1U << 8)) != 0;
        int has_avx512f = (ebx & (1U << 16)) != 0;
        int has_avx512dq = (ebx & (1U << 17)) != 0;
        int has_avx512cd = (ebx & (1U << 28)) != 0;
        int has_avx512bw = (ebx & (1U << 30)) != 0;
        int has_avx512vl = (ebx & (1U << 31)) != 0;

        features.v3 = features.v2_avx && has_avx2 && has_fma && has_bmi1 && has_bmi2 && has_f16c && has_lzcnt && has_movbe;

        int has_avx512_state = (xcr0 & 0xE6U) == 0xE6U;
        features.v4 = features.v3 && has_avx512f && has_avx512dq && has_avx512cd && has_avx512bw && has_avx512vl && has_avx512_state;
    }}

    return features;
}}

static int supports_x86_64(const ihsnpeaks_cpu_features *features) {{
    (void)features;
    return 1;
}}

static int supports_x86_64_v2(const ihsnpeaks_cpu_features *features) {{
    return features->v2;
}}

static int supports_x86_64_v2_avx(const ihsnpeaks_cpu_features *features) {{
    return features->v2_avx;
}}

static int supports_x86_64_v3(const ihsnpeaks_cpu_features *features) {{
    return features->v3;
}}

static int supports_x86_64_v4(const ihsnpeaks_cpu_features *features) {{
    return features->v4;
}}

static const ihsnpeaks_variant_entry ihsnpeaks_variants[] = {{
{table_rows}
}};

static const ihsnpeaks_variant_alias ihsnpeaks_aliases[] = {{
{aliases}
}};

static const char *canonical_variant_name(const char *name) {{
    size_t n = sizeof(ihsnpeaks_aliases) / sizeof(ihsnpeaks_aliases[0]);
    for (size_t i = 0; i < n; ++i) {{
        if (strcmp(name, ihsnpeaks_aliases[i].alias) == 0) return ihsnpeaks_aliases[i].canonical;
    }}
    return name;
}}

static void print_dispatch_variants(const ihsnpeaks_cpu_features *features) {{
    size_t n = sizeof(ihsnpeaks_variants) / sizeof(ihsnpeaks_variants[0]);
    fputs("Compiled ihsnpeaks dispatch variants:\\n", stdout);
    for (size_t i = 0; i < n; ++i) {{
        const ihsnpeaks_variant_entry *entry = &ihsnpeaks_variants[i];
        printf("  %s%s\\n", entry->name, entry->supported(features) ? "" : " (unsupported on this CPU)");
    }}
}}

int main(int argc, char **argv) {{
    ihsnpeaks_cpu_features features = ihsnpeaks_detect_cpu();
    const char *forced = getenv("IHSNPEAKS_DISPATCH");
    size_t n = sizeof(ihsnpeaks_variants) / sizeof(ihsnpeaks_variants[0]);

    if (forced && (strcmp(forced, "help") == 0 || strcmp(forced, "list") == 0)) {{
        print_dispatch_variants(&features);
        return 0;
    }}

    if (forced && forced[0] != '\\0') {{
        const char *canonical = canonical_variant_name(forced);
        for (size_t i = 0; i < n; ++i) {{
            const ihsnpeaks_variant_entry *entry = &ihsnpeaks_variants[i];
            if (strcmp(canonical, entry->name) == 0) {{
                if (!entry->supported(&features)) {{
                    fprintf(stderr, "Requested dispatch variant '%s' is not supported on this CPU.\\n", forced);
                    return 2;
                }}
                return entry->entry(argc, argv);
            }}
        }}
        fprintf(stderr, "Unknown dispatch variant '%s'. Set IHSNPEAKS_DISPATCH=help to list compiled variants.\\n", forced);
        return 2;
    }}

    for (size_t i = 0; i < n; ++i) {{
        const ihsnpeaks_variant_entry *entry = &ihsnpeaks_variants[i];
        if (entry->supported(&features)) return entry->entry(argc, argv);
    }}

    fputs("No supported ihsnpeaks dispatch variant is available.\\n", stderr);
    return 2;
}}
"""


def compile_variant(
    root: Path,
    build_root: Path,
    cc: str,
    objcopy: str,
    stdflag: str,
    base_cflags: list[str],
    variant: Variant,
    scaling_source: Path | None = None,
) -> Path:
    variant_dir = build_root / variant.build_name
    variant_dir.mkdir(parents=True, exist_ok=True)

    scaling_nufft_obj = variant_dir / "nufft1.scaling.o"
    scaling_gen = variant_dir / "scaling_gen"
    scaling_header = variant_dir / "scaling.h"
    wrapper_c = variant_dir / "ihsnpeaks_variant.c"
    variant_obj = variant_dir / "ihsnpeaks_variant.o"

    common_flags = [stdflag, "-D_GNU_SOURCE", "-DHAS_MIMALLOC=0", f"-DMAX_TWIDDLE_REUSE={MAX_TWIDDLE_REUSE}", "-pthread"]
    include_flags = [f"-I{root / 'include'}", f"-I{root / 'src/nufft'}", f"-I{variant_dir}", f"-I{root}"]
    variant_flags = list(variant.cflags)

    if scaling_source is not None:
        print(f"Scaling proxy for {variant.name}: {scaling_source}", flush=True)
        shutil.copyfile(scaling_source, scaling_header)
    else:
        run(
            [
                cc,
                *common_flags,
                "-O3",
                "-ffast-math",
                "-fno-sanitize=all",
                *variant_flags,
                *include_flags,
                "-c",
                str(root / "src/nufft/nufft1.c"),
                "-o",
                str(scaling_nufft_obj),
            ],
            root,
        )
        run(
            [
                cc,
                *common_flags,
                "-O3",
                "-ffast-math",
                "-fno-sanitize=all",
                *variant_flags,
                *include_flags,
                str(root / "src/nufft/scaling.c"),
                str(scaling_nufft_obj),
                "-static",
                "-lm",
                "-o",
                str(scaling_gen),
            ],
            root,
        )
        run([str(scaling_gen), str(scaling_header)], root)

    write_text(wrapper_c, variant_wrapper_source(variant))
    run(
        [
            cc,
            *base_cflags,
            *variant_flags,
            *include_flags,
            "-c",
            str(wrapper_c),
            "-o",
            str(variant_obj),
        ],
        root,
    )
    run([objcopy, "--localize-hidden", str(variant_obj)], root)
    return variant_obj


def main(argv: list[str]) -> int:
    root = repo_root()
    parser = argparse.ArgumentParser(description="Build the static Linux x86-64 release dispatcher.")
    parser.add_argument("--cc", default=os.environ.get("CC", default_target_tool("gcc")))
    parser.add_argument("--objcopy", default=os.environ.get("OBJCOPY", default_target_tool("objcopy")))
    parser.add_argument("--strip", default=os.environ.get("STRIP", default_target_tool("strip")))
    parser.add_argument("--host-cc", default=os.environ.get("HOST_CC", "cc"))
    parser.add_argument("--build-dir", default=str(root / "build/release/linux-x86_64-musl"))
    parser.add_argument("--output", default=str(root / "dist/ihsnpeaks-linux-x86-64"))
    parser.add_argument("--force-all", action="store_true", help="Build every variant even if host flags do not report support.")
    args = parser.parse_args(argv)

    cc = resolve_tool(args.cc, "target compiler")
    objcopy = resolve_tool(args.objcopy, "target objcopy")
    strip = resolve_tool(args.strip, "target strip")
    host_cc = resolve_tool(args.host_cc, "host compiler")
    build_root = Path(args.build_dir).resolve()
    output = Path(args.output).resolve()
    build_root.mkdir(parents=True, exist_ok=True)
    output.parent.mkdir(parents=True, exist_ok=True)

    cross_scaling: dict[str, Path] = {}
    host_machine = platform.machine().lower()
    if host_machine in {"x86_64", "amd64"}:
        variants = list(VARIANTS if args.force_all else host_supported_variants())
    elif host_machine in {"aarch64", "arm64"}:
        variants = list(VARIANTS)
        host_stdflag = detect_stdflag(host_cc, root)
        cross_scaling = arm_proxy_scaling_sources(root, build_root, host_cc, host_stdflag)
    else:
        raise SystemExit(f"release-linux-x86_64-musl requires x86_64 or arm64 host/proxy scaling, got {platform.machine()}")
    print("Release variants: " + ", ".join(variant.name for variant in variants), flush=True)

    stdflag = detect_stdflag(cc, root)
    hwloc_inc, hwloc_lib = ensure_hwloc(root, build_root, cc)
    base_cflags = [
        stdflag,
        "-D_GNU_SOURCE",
        "-DHAS_MIMALLOC=0",
        f"-DMAX_TWIDDLE_REUSE={MAX_TWIDDLE_REUSE}",
        "-Ofast",
        "-fno-sanitize=all",
        "-ffunction-sections",
        "-fdata-sections",
        "-fvisibility=hidden",
        "-pthread",
        f"-I{hwloc_inc}",
    ]

    variant_objects = [
        compile_variant(root, build_root, cc, objcopy, stdflag, base_cflags, variant, cross_scaling.get(variant.name)) for variant in variants
    ]

    dispatcher_c = build_root / "dispatch_main.c"
    dispatcher_o = build_root / "dispatch_main.o"
    write_text(dispatcher_c, dispatcher_source(variants))
    run(
        [
            cc,
            stdflag,
            "-D_GNU_SOURCE",
            "-O2",
            "-fno-sanitize=all",
            "-ffunction-sections",
            "-fdata-sections",
            "-march=x86-64",
            "-mtune=generic",
            "-pthread",
            f"-I{hwloc_inc}",
            "-c",
            str(dispatcher_c),
            "-o",
            str(dispatcher_o),
        ],
        root,
    )
    run(
        [
            cc,
            "-static",
            "-pthread",
            "-Wl,--gc-sections",
            str(dispatcher_o),
            *(str(obj) for obj in variant_objects),
            str(hwloc_lib),
            "-lm",
            "-o",
            str(output),
        ],
        root,
    )
    run([strip, "-s", str(output)], root)
    print(f"Release binary: {output}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
