#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
from pathlib import Path

from variants import repo_root


MAX_TWIDDLE_REUSE = "8"


def run(cmd: list[str], cwd: Path) -> None:
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def resolve_tool(tool: str, role: str) -> str:
    resolved = shutil.which(tool)
    if resolved:
        return resolved
    raise SystemExit(f"Required {role} tool '{tool}' was not found. Install Zig/LLVM or pass the tool explicitly.")


def first_existing_tool(candidates: tuple[str, ...]) -> str:
    for candidate in candidates:
        if shutil.which(candidate):
            return candidate
    return candidates[0]


def detect_stdflag_cmd(cc_cmd: list[str], cwd: Path) -> str:
    for stdflag in ("-std=gnu23", "-std=gnu2x"):
        probe = subprocess.run(
            [*cc_cmd, stdflag, "-x", "c", "-", "-fsyntax-only"],
            input="constexpr int x = 1; int main(void){return x - 1;}\n",
            text=True,
            cwd=cwd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if probe.returncode == 0:
            return stdflag
    return "-std=gnu11"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def try_generate_proxy_scaling(root: Path, build_root: Path, host_cc: str, stdflag: str, name: str, cflags: list[str]) -> Path | None:
    proxy_dir = build_root / "scaling-proxy" / name
    proxy_dir.mkdir(parents=True, exist_ok=True)
    nufft_obj = proxy_dir / "nufft1.o"
    scaling_gen = proxy_dir / "scaling_gen"
    scaling_header = proxy_dir / "scaling.h"
    common_flags = [stdflag, "-D_GNU_SOURCE", "-DHAS_MIMALLOC=0", f"-DMAX_TWIDDLE_REUSE={MAX_TWIDDLE_REUSE}", "-pthread"]
    include_flags = [f"-I{root / 'include'}", f"-I{root / 'src/nufft'}", f"-I{proxy_dir}", f"-I{root}"]

    try:
        run(
            [
                host_cc,
                *common_flags,
                "-O3",
                "-ffast-math",
                "-fno-sanitize=all",
                *cflags,
                *include_flags,
                "-c",
                str(root / "src/nufft/nufft1.c"),
                "-o",
                str(nufft_obj),
            ],
            root,
        )
        run(
            [
                host_cc,
                *common_flags,
                "-O3",
                "-ffast-math",
                "-fno-sanitize=all",
                *cflags,
                *include_flags,
                str(root / "src/nufft/scaling.c"),
                str(nufft_obj),
                "-static",
                "-lm",
                "-o",
                str(scaling_gen),
            ],
            root,
        )
        run([str(scaling_gen), str(scaling_header)], root)
    except subprocess.CalledProcessError:
        print(f"Scaling proxy {name} could not be generated.", flush=True)
        return None

    return scaling_header


def macos_scaling_source(root: Path, build_root: Path, host_cc: str, stdflag: str) -> Path:
    host_machine = platform.machine().lower()
    if host_machine in {"x86_64", "amd64"}:
        source = try_generate_proxy_scaling(root, build_root, host_cc, stdflag, "x86-64-v2", ["-march=x86-64-v2", "-mtune=generic"])
        if source is None:
            raise SystemExit("Unable to generate x86-64-v2 proxy scaling for macOS ARM64 release.")
        print(f"macOS ARM64 scaling: reusing x86-64-v2 proxy {source}", flush=True)
        return source

    if host_machine in {"aarch64", "arm64"}:
        source = try_generate_proxy_scaling(root, build_root, host_cc, stdflag, "arm128", ["-march=armv8-a+simd"])
        if source is None:
            source = try_generate_proxy_scaling(root, build_root, host_cc, stdflag, "arm64", ["-march=armv8-a"])
        if source is None:
            raise SystemExit("Unable to generate ARM 128-bit proxy scaling for macOS ARM64 release.")
        print(f"macOS ARM64 scaling: reusing ARM 128-bit proxy {source}", flush=True)
        return source

    raise SystemExit(f"Unsupported host architecture '{host_machine}' for macOS ARM64 scaling generation.")


def target_cc_command(zig: str, macos_min_version: str, sdk_path: str | None) -> list[str]:
    cmd = [zig, "cc", "-target", "aarch64-macos", f"-mmacosx-version-min={macos_min_version}"]
    if sdk_path:
        cmd.extend(["-isysroot", sdk_path])
    return cmd


def variant_wrapper_source() -> str:
    return """/* Generated by dispatch/build_release_macos_arm64.py. */
#include "src/utils/compat.h"
#include "src/main.c"
#include "src/nufft/nufft1.c"
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a macOS ARM64 release binary with Zig.")
    parser.add_argument("--build-dir", type=Path, default=Path("build/release/macos-arm64"))
    parser.add_argument("--output", type=Path, default=Path("dist/ihsnpeaks-macos-arm64"))
    parser.add_argument("--zig", default=os.environ.get("ZIG", "zig"))
    parser.add_argument("--host-cc", default=os.environ.get("HOST_CC", os.environ.get("CC", "cc")))
    parser.add_argument("--strip", default=os.environ.get("STRIP", first_existing_tool(("llvm-strip", "strip"))))
    parser.add_argument("--macos-min-version", default=os.environ.get("MACOS_MIN_VERSION", "12.0"))
    parser.add_argument("--sdk", default=os.environ.get("MACOS_SDK_PATH") or os.environ.get("MACOS_SDK"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root = repo_root()
    build_root = args.build_dir if args.build_dir.is_absolute() else root / args.build_dir
    output = args.output if args.output.is_absolute() else root / args.output
    zig = resolve_tool(args.zig, "Zig compiler")
    host_cc = resolve_tool(args.host_cc, "host compiler")
    strip = resolve_tool(args.strip, "strip")

    sdk_path = args.sdk if args.sdk else None
    if sdk_path and not Path(sdk_path).exists():
        raise SystemExit(f"MACOS_SDK_PATH points to a missing path: {sdk_path}")

    host_stdflag = detect_stdflag_cmd([host_cc], root)
    target_cmd = target_cc_command(zig, args.macos_min_version, sdk_path)
    target_stdflag = detect_stdflag_cmd(target_cmd, root)
    print(f"Host C standard: {host_stdflag}", flush=True)
    print(f"Target C standard: {target_stdflag}", flush=True)

    scaling_source = macos_scaling_source(root, build_root, host_cc, host_stdflag)
    variant_dir = build_root / "arm64"
    variant_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(scaling_source, variant_dir / "scaling.h")

    wrapper = variant_dir / "ihsnpeaks_macos_arm64.c"
    obj = variant_dir / "ihsnpeaks_macos_arm64.o"
    write_text(wrapper, variant_wrapper_source())

    include_flags = [f"-I{root / 'include'}", f"-I{root / 'src/nufft'}", f"-I{variant_dir}", f"-I{root}"]
    common_flags = [
        target_stdflag,
        "-D_DARWIN_C_SOURCE",
        "-DHAS_MIMALLOC=0",
        "-Dconstexpr=const",
        f"-DMAX_TWIDDLE_REUSE={MAX_TWIDDLE_REUSE}",
        "-O3",
        "-ffast-math",
        "-fno-sanitize=all",
        "-ffunction-sections",
        "-fdata-sections",
        "-fvisibility=hidden",
        *include_flags,
    ]

    run([*target_cmd, *common_flags, "-c", str(wrapper), "-o", str(obj)], root)
    output.parent.mkdir(parents=True, exist_ok=True)
    run([*target_cmd, "-Wl,-dead_strip", str(obj), "-lm", "-o", str(output)], root)
    try:
        run([strip, "-x", str(output)], root)
    except subprocess.CalledProcessError:
        print(f"Warning: strip failed for {output}; keeping unstripped Mach-O binary.", flush=True)
    print(f"macOS ARM64 release binary: {output}", flush=True)


if __name__ == "__main__":
    main()
